name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - master  # Trigger on push to the 'master' branch
    paths:
      - app.py  # Trigger if app.py is changed
      - templates/**  # Trigger if any file in the templates folder is changed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.3

      - name: Deploy app.py and templates to PythonAnywhere
        run: |
          pip install pythonanywhere
          scp -o StrictHostKeyChecking=no app.py Mrutyunjaya07@ssh.pythonanywhere.com:/home/Mrutyunjaya07/my_site/app.py
          scp -o StrictHostKeyChecking=no -r templates/ Mrutyunjaya07@ssh.pythonanywhere.com:/home/Mrutyunjaya07/my_site/templates/
          ssh -o StrictHostKeyChecking=no Mrutyunjaya07@ssh.pythonanywhere.com 'python3 /home/Mrutyunjaya07/my_site/app.py && pythonanywhere webapp reload Mrutyunjaya07.pythonanywhere.com'
        env:
          PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
