name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - master  # Trigger on push to the 'main' branch
    paths:
      - demo.py  # Trigger only if demo.py is changed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.3

      - name: Deploy demo.py to PythonAnywhere
        run: |
          pip install pythonanywhere
          scp -o StrictHostKeyChecking=no demo.py Mrutyunjaya07@ssh.pythonanywhere.com:/home/Mrutyunjaya07/my_site/demo.py
          ssh -o StrictHostKeyChecking=no Mrutyunjaya07@ssh.pythonanywhere.com 'python3 /home/Mrutyunjaya07/my_site/demo.py && pythonanywhere webapp reload Mrutyunjaya07.pythonanywhere.com'
        env:
          PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
